/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import crudlp.*;
import factory.ConnectionFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Aluno;
import dao.AlunoDAO;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.io.*;
import java.time.*;
import java.time.format.*;


/**
 *
 * @author Juliano
 */
public class AlunoGUI extends javax.swing.JFrame {
      static Connection con = null; 
    
    /**
     * Creates new form FramePrincipal
     */
    public AlunoGUI() {
        initComponents();
           AlunoDAO alunodao = new AlunoDAO();
        alunodao.seleciona(tblregistro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCadastrar = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lclcpf = new javax.swing.JLabel();
        lblnascimento = new javax.swing.JLabel();
        lblaltura = new javax.swing.JLabel();
        lblpeso = new javax.swing.JLabel();
        lblimc = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        txtcpf = new javax.swing.JTextField();
        txtnascimento = new javax.swing.JTextField();
        txtaltura = new javax.swing.JTextField();
        txtpeso = new javax.swing.JTextField();
        txtimc = new javax.swing.JTextField();
        lblregistro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblregistro = new javax.swing.JTable();
        btninserir = new javax.swing.JButton();
        btnexcluir = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        btncadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Cálculo de IMC");

        lblCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCadastrar.setText("Cadastrar");

        lblnome.setText("Nome");

        lclcpf.setText("CPF");

        lblnascimento.setText("Nascimento");

        lblaltura.setText("Altura");

        lblpeso.setText("Peso");

        lblimc.setText("IMC");

        lblregistro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblregistro.setText("Registro");

        tblregistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF ", "Nascimento", "Altura", "Peso", "IMC"
            }
        ));
        jScrollPane1.setViewportView(tblregistro);

        btninserir.setText("Inserir");
        btninserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninserirActionPerformed(evt);
            }
        });

        btnexcluir.setText("Excluir");
        btnexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexcluirActionPerformed(evt);
            }
        });

        btnatualizar.setText("Atualizar");
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });

        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        btncadastrar.setText("Salvar Arquivo");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btninserir, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblnome)
                                .addGap(93, 93, 93)
                                .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lclcpf)
                                .addGap(93, 93, 93)
                                .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblpeso)
                                    .addComponent(lblnascimento)
                                    .addComponent(lblimc))
                                .addGap(93, 93, 93)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtimc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblaltura)
                                .addGap(93, 93, 93)
                                .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(lblCadastrar))
                    .addComponent(btnlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblregistro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btncadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnexcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnatualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCadastrar)
                    .addComponent(lblregistro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnome)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lclcpf)
                            .addComponent(txtcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblnascimento)
                            .addComponent(txtnascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblaltura)
                            .addComponent(txtaltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblpeso)
                            .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblimc)
                            .addComponent(txtimc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(btninserir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnexcluir)
                    .addComponent(btnatualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrar)
                    .addComponent(btnlimpar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninserirActionPerformed
        String nome = txtnome.getText();
        String cpf = txtcpf.getText();
        String nascimento = txtnascimento.getText();
        String altura = txtaltura.getText();
        String peso = txtpeso.getText();
        
        double a1 = Double.valueOf(altura).doubleValue();
        double p1  = Double.valueOf(peso).doubleValue();
        double imc1 = ( p1 / (a1 * a1));
        
        String strResultado = Double.toString(imc1);
        txtimc.setText(strResultado);
        String imc = txtimc.getText();
        
    
        AlunoDAO alunodao = new AlunoDAO();
        
        
        Aluno aluno = new Aluno(nome, cpf, nascimento, altura, peso, imc);
        alunodao.adiciona(aluno);
        
        alunodao.seleciona(tblregistro);
        
      
    }//GEN-LAST:event_btninserirActionPerformed

    private void btnexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexcluirActionPerformed
        AlunoDAO alunodao = new AlunoDAO();
        
        
        int row = tblregistro.getSelectedRow();
        String valor = tblregistro.getModel().getValueAt(row,1).toString();
        alunodao.deleta(valor);
        
        alunodao.seleciona(tblregistro);
        
        
    }//GEN-LAST:event_btnexcluirActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        DefaultTableModel tbl = (DefaultTableModel)tblregistro.getModel();
      
            int SelectedRowIndex = tblregistro.getSelectedRow();
            
            String nnome = tbl.getValueAt(SelectedRowIndex, 0).toString();
            String ncpf = tbl.getValueAt(SelectedRowIndex, 1).toString();
            String nnascimento = tbl.getValueAt(SelectedRowIndex, 2).toString();
            String naltura = tbl.getValueAt(SelectedRowIndex, 3).toString();
            String npeso = tbl.getValueAt(SelectedRowIndex, 4).toString();
            String nimc = tbl.getValueAt(SelectedRowIndex, 5).toString();
            
            String novonome = JOptionPane.showInputDialog(null, "Digite o novo nome", nnome);
            String novocpf = JOptionPane.showInputDialog(null, "Digite o novo cpf", ncpf);
            String novonascimento = JOptionPane.showInputDialog(null, "Digite o novo nascimento", nnascimento);
            String novoaltura = JOptionPane.showInputDialog(null, "Digite o novo altura", naltura);
            String novopeso = JOptionPane.showInputDialog(null, "Digite o novo peso", npeso);
            double daltura = Double.parseDouble(novoaltura);
            double dpeso = Double.parseDouble(novopeso);
            double dimc = dpeso/ (daltura * daltura);
            String novoimc = Double.toString(dimc);
            
            AlunoDAO alunodao = new AlunoDAO();
        
        
             Aluno aluno = new Aluno(novonome, novocpf, novonascimento, novoaltura, novopeso, novoimc);
             alunodao.atualiza(aluno, ncpf);
        
             alunodao.seleciona(tblregistro);
            
        
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed
        txtnome.setText("");
        txtcpf.setText("");
        txtnascimento.setText("");
        txtaltura.setText("");
        txtpeso.setText("");
        txtimc.setText("");
        
        
    }//GEN-LAST:event_btnlimparActionPerformed

    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        // TODO add your handling code here:
        int row = tblregistro.getSelectedRow();
        String nome = tblregistro.getModel().getValueAt(row,0).toString();
        String cpf = tblregistro.getModel().getValueAt(row,1).toString();
        double imc = Double.parseDouble(tblregistro.getModel().getValueAt(row,5).toString());
        String classificacao = "";
        
        if (imc < 18.5) {
             classificacao = "Baixo peso";
        } else if (imc < 25) {
             classificacao = "Peso normal";
        } else if (imc < 30) {
             classificacao = "Sobrepeso";
        } else if (imc < 35) {
             classificacao = "Obesidade grau 1";
        } else if (imc < 40) {
             classificacao = "Obesidade grau 2";
        } else {
             classificacao = "Obesidade grau 3";
        }
        
        
        
        
        try {
            DateTimeFormatter formato =  DateTimeFormatter.ofPattern("dd/MM/yyyy");
            File file = new File("File.txt");
            FileWriter filewriter = new FileWriter(file, true);
            BufferedWriter bufferedwriter = new BufferedWriter(filewriter);
            bufferedwriter.write(LocalDateTime.now().format(formato));
            bufferedwriter.write(" " + nome);
            bufferedwriter.write(" " + cpf);
            bufferedwriter.write(" " + imc);
            bufferedwriter.write(" " + classificacao);
            bufferedwriter.newLine();
            bufferedwriter.close();
        } catch (IOException ex){
            
        }
       
    }//GEN-LAST:event_btncadastrarActionPerformed

 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        
        try {
                con = DriverManager.getConnection("jdbc:mysql://localhost/db_alunos", "root", "fatec");
               
            }
        catch(SQLException excecao){
            throw new RuntimeException(excecao);
        }
    
     
        
        
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnexcluir;
    private javax.swing.JButton btninserir;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCadastrar;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblaltura;
    private javax.swing.JLabel lblimc;
    private javax.swing.JLabel lblnascimento;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lblpeso;
    private javax.swing.JLabel lblregistro;
    private javax.swing.JLabel lclcpf;
    private javax.swing.JTable tblregistro;
    private javax.swing.JTextField txtaltura;
    private javax.swing.JTextField txtcpf;
    private javax.swing.JTextField txtimc;
    private javax.swing.JTextField txtnascimento;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtpeso;
    // End of variables declaration//GEN-END:variables
}
